<?php


class Point3d extends Point2d
{
    public float $z;

    public function __construct(float $x, float $y, float $z)
    {
        parent::__construct($x, $y);
        $this->z = $z;
    }

    /**
     * @param float $z
     */
    public function setZ(float $z): void
    {
        $this->z = $z;
    }

    /**
     * @return float
     */
    public function getZ(): float
    {
        return $this->z;
    }

    public function setXYZ(float $x, float $y, float $z): void
    {
        parent::setXY();
        $this->z = $z;
    }

    public function getXYZ(): array
    {
       $arr = parent::getXY();
       $arr [] = $this->z;
       return $arr;
    }

    public function __toString(): string
    {
        return "A {x: " . $this->x . ", y: " . $this->y . ", z: " . $this->z . "}";
        /*parent::__toString(); // TODO: Change the autogenerated stub*/
    }
}